In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('disease_indicators.csv')

In [3]:
df.columns

Index(['Unnamed: 0', 'YearStart', 'LocationAbbr', 'Question', 'DataValueUnit',
       'DataValueType', 'DataValue', 'DatavalueFootnote', 'LowConfidenceLimit',
       'HighConfidenceLimit', 'Stratification1', 'StratificationCategory1',
       'GeoLocation', 'US_Avg', 'Diff_from_US', 'Latitude', 'Longitude'],
      dtype='object')

In [4]:
df = df[(df['Question']=='Poverty') & (df['YearStart']==2016)]

In [23]:
df = df[['LocationAbbr','DataValue','Stratification1','Latitude','Longitude']]
df = df.sort_values(by=['Stratification1','LocationAbbr'])
df

,LocationAbbr,DataValue,Stratification1,Latitude,Longitude
37796,AK,24.7,American Indian or Alaska Native,64.845080,-147.722059
37803,AL,NaN,American Indian or Alaska Native,32.840571,-86.631861
37808,AR,NaN,American Indian or Alaska Native,34.748650,-92.274491
37816,AZ,34.4,American Indian or Alaska Native,34.865970,-111.763811
37824,CA,23.9,American Indian or Alaska Native,37.638640,-121.000000
37832,CO,NaN,American Indian or Alaska Native,38.843841,-106.133611
37840,CT,NaN,American Indian or Alaska Native,41.562661,-72.649841
37848,DC,NaN,American Indian or Alaska Native,38.907192,-77.036871
37856,DE,NaN,American Indian or Alaska Native,39.008831,-75.577741
37864,FL,NaN,American Indian or Alaska Native,28.932040,-81.928961
37872,GA,NaN,American Indian or Alaska Native,32.839681,-83.627580
37880,HI,NaN,American Indian or Alaska Native,21.304850,-157.857749
37888,IA,NaN,American Indian or Alaska Native,42.469401,-93.816491
37896,ID,NaN,American Indian or Alaska Native,43.682630,-114.363730
37904,IL,NaN,American Indian or Alaska Native,40.485010,-88.997710
37912,IN,NaN,American Indian or Alaska Native,39.766910,-86.149960
37920,KS,NaN,American Indian or Alaska Native,38.347740,-98.200781
37929,KY,NaN,American Indian or Alaska Native,37.645970,-84.774971
37937,LA,NaN,American Indian or Alaska Native,31.312661,-92.445680
37945,MA,NaN,American Indian or Alaska Native,42.276870,-72.082691
37953,MD,NaN,American Indian or Alaska Native,39.290581,-76.609260
37961,ME,NaN,American Indian or Alaska Native,45.254229,-68.985031
37969,MI,NaN,American Indian or Alaska Native,44.661320,-84.714390
37977,MN,NaN,American Indian or Alaska Native,46.355649,-94.794201
37985,MO,NaN,American Indian or Alaska Native,38.635791,-92.566300
37993,MS,NaN,American Indian or Alaska Native,32.745510,-89.538031
38001,MT,26.2,American Indian or Alaska Native,47.066529,-109.424421
38009,NC,23.9,American Indian or Alaska Native,35.466221,-79.159250
38017,ND,NaN,American Indian or Alaska Native,47.475320,-100.118421
38025,NE,NaN,American Indian or Alaska Native,41.641041,-99.365721
...,...,...,...,...,...
37974,MN,7.0,"White, non-Hispanic",46.355649,-94.794201
37982,MO,11.5,"White, non-Hispanic",38.635791,-92.566300
37990,MS,13.0,"White, non-Hispanic",32.745510,-89.538031
37998,MT,12.0,"White, non-Hispanic",47.066529,-109.424421
38006,NC,10.8,"White, non-Hispanic",35.466221,-79.159250
38014,ND,7.7,"White, non-Hispanic",47.475320,-100.118421
38022,NE,8.5,"White, non-Hispanic",41.641041,-99.365721
38030,NH,6.7,"White, non-Hispanic",43.655950,-71.500361
38038,NJ,6.4,"White, non-Hispanic",40.130570,-74.273691
38046,NM,11.9,"White, non-Hispanic",34.520881,-106.240581
38054,NV,9.7,"White, non-Hispanic",39.493240,-117.071841
38062,NY,9.6,"White, non-Hispanic",42.827001,-75.543970
38070,OH,11.2,"White, non-Hispanic",40.060210,-82.404260
38076,OK,12.3,"White, non-Hispanic",35.472031,-97.521070
38084,OR,11.1,"White, non-Hispanic",44.567449,-120.155031
38091,PA,9.2,"White, non-Hispanic",40.793730,-77.860700
39359,PR,NaN,"White, non-Hispanic",18.220833,-66.590149
38103,RI,9.6,"White, non-Hispanic",41.708280,-71.522470
38110,SC,10.1,"White, non-Hispanic",33.998821,-81.045371
38118,SD,8.4,"White, non-Hispanic",44.353130,-100.373531
38126,TN,12.5,"White, non-Hispanic",35.680941,-85.774491
37777,TX,8.9,"White, non-Hispanic",31.827240,-99.426770
38139,US,10.0,"White, non-Hispanic",NaN,NaN
38146,UT,8.1,"White, non-Hispanic",39.360700,-111.587131
38154,VA,8.3,"White, non-Hispanic",37.542681,-78.457890
38162,VT,11.4,"White, non-Hispanic",43.625381,-72.517641
38170,WA,9.0,"White, non-Hispanic",47.522279,-120.470011
38178,WI,8.7,"White, non-Hispanic",44.393191,-89.816371
38186,WV,17.4,"White, non-Hispanic",38.665510,-80.712640
38194,WY,10.1,"White, non-Hispanic",43.235541,-108.109830

In [17]:
g = df.groupby('LocationAbbr')
id_df = g['DataValue'].apply(lambda x: pd.Series(x.values)).unstack()
id_df.columns = g.agg({'Stratification1':lambda x:x.tolist()}).reset_index()['Stratification1'][0]
id_df

,American Indian or Alaska Native,"Asian, non-Hispanic","Black, non-Hispanic",Female,Hispanic,Male,Overall,"White, non-Hispanic"
LocationAbbr,,,,,,,,
AK,24.7,NaN,NaN,10.6,16.1,9.3,9.9,6.3
AL,NaN,11.1,27.4,18.6,30.1,15.4,17.1,12.2
AR,NaN,NaN,28.7,18.6,26.7,15.8,17.2,13.7
AZ,34.4,13.2,22.0,17.2,23.5,15.5,16.4,10.9
CA,23.9,11.3,21.9,15.4,19.1,13.3,14.3,9.5
CO,NaN,10.2,19.7,12.0,17.9,10.1,11.0,8.3
CT,NaN,8.3,18.4,10.6,20.4,8.9,9.8,5.9
DC,NaN,NaN,28.0,19.7,17.8,17.3,18.6,7.2
DE,NaN,NaN,17.7,12.9,24.5,10.3,11.7,7.6
FL,NaN,12.2,22.7,15.8,18.9,13.6,14.7,10.6
GA,NaN,11.9,22.5,17.4,24.3,14.4,16.0,10.8
HI,NaN,6.5,NaN,10.3,10.8,8.3,9.3,8.6
IA,NaN,13.9,35.2,13.1,23.1,10.4,11.8,9.7
ID,NaN,NaN,NaN,15.2,22.1,13.5,14.4,12.8
IL,NaN,11.6,26.6,14.2,17.2,11.6,13.0,8.8
IN,NaN,22.9,28.7,15.4,24.2,12.7,14.1,11.1
KS,NaN,13.5,24.5,13.2,18.2,11.0,12.1,10.0
KY,NaN,NaN,30.2,20.5,30.6,16.4,18.5,16.8
LA,NaN,15.7,34.3,22.1,22.2,18.1,20.2,12.4
MA,NaN,13.6,18.8,11.5,26.5,9.3,10.4,6.7
MD,NaN,6.8,13.6,10.4,12.4,8.9,9.7,7.1
ME,NaN,NaN,NaN,13.6,17.9,11.3,12.5,11.5
MI,NaN,16.4,28.8,16.0,23.2,13.9,15.0,11.6
MN,NaN,16.1,29.9,10.8,18.1,9.0,9.9,7.0
MO,NaN,15.3,24.9,15.1,24.1,12.8,14.0,11.5
MS,NaN,NaN,32.3,22.8,24.8,18.7,20.8,13.0
MT,26.2,NaN,NaN,13.8,19.1,12.9,13.3,12.0
NC,23.9,12.0,23.5,16.6,27.3,14.1,15.4,10.8
ND,NaN,NaN,NaN,10.8,20.4,10.7,10.7,7.7
NE,NaN,NaN,26.2,12.6,22.7,10.3,11.4,8.5
NH,NaN,NaN,NaN,8.1,13.8,6.5,7.3,6.7
NJ,NaN,6.8,17.2,11.4,18.6,9.4,10.4,6.4
NM,32.9,NaN,NaN,21.4,24.1,18.3,19.8,11.9
NV,NaN,9.4,21.8,14.9,19.0,12.7,13.8,9.7
NY,NaN,16.3,20.3,16.1,24.2,13.3,14.7,9.6
OH,NaN,15.1,31.0,15.9,24.9,13.2,14.6,11.2
OK,22.1,14.7,29.0,17.6,26.0,15.0,16.3,12.3
OR,NaN,14.3,26.2,14.5,22.6,12.1,13.3,11.1
PA,NaN,13.8,26.2,14.0,30.0,11.7,12.9,9.2
PR,NaN,NaN,NaN,45.2,43.6,41.6,43.5,NaN
RI,NaN,NaN,NaN,13.6,21.9,12.0,12.8,9.6
SC,NaN,10.4,24.8,16.6,25.8,13.9,15.3,10.1
SD,48.9,NaN,NaN,14.9,25.2,11.6,13.3,8.4
TN,NaN,12.2,26.3,17.1,27.7,14.4,15.8,12.5
TX,13.7,10.7,20.3,17.0,22.3,14.2,15.6,8.9
US,26.9,11.7,23.8,15.2,21.0,12.8,14.0,10.0
UT,NaN,12.2,NaN,11.2,17.6,9.3,10.2,8.1
VA,NaN,7.3,18.2,12.0,16.3,9.9,11.0,8.3
VT,NaN,NaN,NaN,12.5,21.4,11.2,11.9,11.4
WA,24.7,9.2,23.0,12.2,19.4,10.3,11.3,9.0
WI,NaN,18.1,33.0,12.8,22.6,10.7,11.8,8.7
WV,NaN,NaN,26.6,19.4,22.8,16.4,17.9,17.4
WY,NaN,NaN,NaN,12.2,16.7,10.5,11.3,10.1

In [18]:
id_df.to_csv('poverty_demographics.csv')